// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://npjwtmnovjotihmqrzyb.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im5wand0bW5vdmpvdGlobXFyenliIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTQ2MDY3NDksImV4cCI6MjA3MDE4Mjc0OX0.DJfwyG2GEfxRht5xPhYZc0RjLIh07nOdjc6oVmMvXgg";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});